# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "243892f3360adb4d37e8d85bfc78792b"
name = "roast-it-app"
handle = "roast-it-app"
application_url = "https://forecasts-score-neighbor-turbo.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_script_tags"

[auth]
redirect_urls = [
  "https://forecasts-score-neighbor-turbo.trycloudflare.com/auth/callback",
  "https://forecasts-score-neighbor-turbo.trycloudflare.com/auth/shopify/callback",
  "https://forecasts-score-neighbor-turbo.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
